<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-17T15:08:22 AST" name="Default suite" finished-at="2023-01-17T15:08:42 AST" duration-ms="20310">
    <groups>
    </groups>
    <test started-at="2023-01-17T15:08:22 AST" name="Default test" finished-at="2023-01-17T15:08:42 AST" duration-ms="20310">
      <class name="SmartBuy">
        <test-method is-config="true" signature="smart_Buy()[pri:0, instance:SmartBuy@2e005c4b]" started-at="2023-01-17T15:08:22 AST" name="smart_Buy" finished-at="2023-01-17T15:08:40 AST" duration-ms="17698" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- smart_Buy -->
        <test-method signature="Test_Adding_item_Samsung_50_inch()[pri:0, instance:SmartBuy@2e005c4b]" started-at="2023-01-17T15:08:40 AST" name="Test_Adding_item_Samsung_50_inch" finished-at="2023-01-17T15:08:42 AST" duration-ms="2272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Adding_item_Samsung_50_inch -->
        <test-method signature="check_the_correct_price()[pri:0, instance:SmartBuy@2e005c4b]" started-at="2023-01-17T15:08:42 AST" name="check_the_correct_price" finished-at="2023-01-17T15:08:42 AST" duration-ms="139" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [ahmad] but found [Smart Buy | Homepage For Web],
expected [3547] but found [369.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [ahmad] but found [Smart Buy | Homepage For Web],
expected [3547] but found [369.0]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at SmartBuy.check_the_correct_price(SmartBuy.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_the_correct_price -->
      </class> <!-- SmartBuy -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
